### ISSUE TITLE
具体看前排提醒吧，前排提醒那个人把那家公司坑的不轻，公司貌似没钱了。

### ISSUE THREAD

**Issue by policeMan666** [it-blacklist/it-blacklist.github.io#459]
详情看前排提醒，某人php技术不行，他也完全不写php了，现在偷已离职的前端代码开始写前端了，要祸害前端岗位了，大家小心。莫得任何技术只会混加班甩锅坑人，坏，懒，诈，差的代表。让他处理解决问题，不好好沟通，还要各种喷你，贬低别人抬高自己。以前乱改后台代码，现在乱改前端代码，坑走了不少人，这公司快没钱发工资了，原因自己想吧。很大程度和这个人写的接口有直接关系。因为他掉了好多单子，#446那个一点建议就是他本人，威胁恐吓小程序开发者，此人的是github[yinwz](https://github.com/yinwz)

**Comment by yinwz** [comment]
首先，我不是那个某东。
其次，用小号，张口就来，还言之凿凿的，就乱喷，有意思吗

**Comment by policeMan666** [comment]
第一这是大号，第二，你这么护主啊？怎么证明你不是？不是的话让你发某东是dog，你敢发吗？第三出来混迟早要还，干的缺魂事儿得罪公司所有人，狡辩什么啊？哈哈哈哈，你就是某东！鉴定完毕

**Comment by yinwz** [comment]
> 

一个刚申请的大号，呵呵
