### ISSUE TITLE
大凡

### ISSUE THREAD

**Issue by LateAutumnWindow** [it-blacklist/it-blacklist.github.io#474]
垃圾外包，垃圾！垃圾！垃圾外包！
为了金钱专坑程序员！

**Comment by hlq0508** [comment]
客观评价，我也是从大凡离职出来的，公司还给了补偿，感觉相比其他小公司还是正规的。

**Comment by alon1982** [comment]
坑你什么了？我现在还在，五险一金双休，没能力被开除在这里叨逼叨
