### ISSUE TITLE
用户量少了

### ISSUE THREAD

**Issue by youyudehuzha** [it-blacklist/it-blacklist.github.io#575]
自从迁移到这个地方，用户量明显少了很多很多啊！

**Comment by q727155121** [comment]
也是没办法，好像被哪个公司给弄了

**Comment by youyudehuzha** [comment]
这么好个平台
----- 原始邮件 -----
发件人：q727155121 ***@***.***>
收件人："it-blacklist/it-blacklist.github.io" ***@***.***>
抄送人：忧郁的胡渣 ***@***.***>,  Author ***@***.***>
主题：Re:_[it-blacklist/it-blacklist.github.io]_用户量少了_(Issue_#575)
日期：2022年07月25日 15点40分



也是没办法，好像被哪个公司给弄了



&mdash;
